### ISSUE TITLE
laser scan seems off at higher distances.

### ISSUE THREAD

**Issue by smits** [Intermodalics/tango_ros#148]
![image](https://cloud.githubusercontent.com/assets/111771/22825309/b33ed3da-ef8c-11e6-8a91-0d1df09b1cec.png)

As you can see in the figure (topdown ortho view in RVIZ) the laserscan does not match the pointcloud at further distances.

**Comment by PerrineAguiar** [comment]
It might be due to the laser scan max range that we set to 6 meters.

**Comment by smits** [comment]
Could we fix this somehow, I would set the max range to the same as the max pointcloud readings.

**Comment by PerrineAguiar** [comment]
This issue could not be reproduced, it might have been some ghost points.
Still a PR will be opened to set the max range the same as the max from pointcloud.
