### ISSUE TITLE
IMU timestamp not in sync with start-of-service

### ISSUE THREAD

**Issue by smits** [Intermodalics/tango_ros#156]
When trying to visualize the IMU in rviz with start-of-service as fixed frame I get the following error:

For frame [imu]: No transform to fixed frame [start_of_service]. TF error: [Lookup would require extrapolation into the future. Requested time 1487337410.255000000 but the latest data is at time 1487240508.901808739, when looking up transform from frame [imu] to frame [start_of_service]]

**Comment by jubeira** [comment]
JFYI, I tried to reproduce the issue but I couldn't. I checked that the timestamp of the imu in tf_static corresponds to the starting time, and it is republished only on each dynamic reconfigure (i.e, it is not constantly updated as other tfs), but the timestamps seemed OK to me.
