### ISSUE TITLE
Make tango ros repo ok for going public

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#18]
- [x] Clean/Make Readme files
- [x] Add doc in code
- [x] Add license
- [x] Add maintainer
- [x] Add an Intermodalics disclaimer
- [x] Check licenses of used libraries
- [x] Find proper name for app and packages
- [x] Write ros wiki

**Comment by smits** [comment]
ROS wiki created: http://wiki.ros.org/tango_ros_streamer

**Comment by PerrineAguiar** [comment]
@smits :+1:
