### ISSUE TITLE
ROS service headers not visible to tango_ros_streamer package

### ISSUE THREAD

**Issue by fishcu** [Intermodalics/tango_ros#257]
Issue: When cloning the repo, the header files, generated from the ROS services (*.srv files) are not visible to the tango_ros_streamer package. "catkin build" will fail on this package.

Hacky fix: Copy the include files (which are really just symlinks) from ".../tango_ros_ws/devel/include" to ".../tango_ros_ws/src/tango_ros/third_party/roscpp_android_ndk/include".

How would this be properly fixed? I had a look at some package.xmls and CMakeLists.txts, but everything seems OK...

**Comment by PerrineAguiar** [comment]
@fishcu Thanks for taking a look, #269 should fix this issue.
