### ISSUE TITLE
Tango connection timeout, unable to reconnect

### ISSUE THREAD

**Issue by mcopejans** [Intermodalics/tango_ros#281]
If Tango connection timed out after 50 attempts, it is not possible to reconnect as follows: going to settings activity, make Tango change, click snackbar to reconnect.

Logcat output indicates a null object reference error in `/tango/connect` service call:
```
05-19 10:22:04.182 17302-17302/eu.intermodalics.tango_ros_streamer E/ngo_service_client_node: Error while calling: /tango/connect, message: Attempt to invoke virtual method 'org.jboss.netty.channel.Channel org.ros.internal.transport.tcp.TcpClient.getChannel()' on a null object reference
```

**Comment by eric-schleicher** [comment]
I've had this happen when killing the connected ros process (remotely).

To fix, I've either rebooted the phone (phab2 pro) **OR** gone into the setting and stopped tango core.

doing the latter i was ultimately successful in getting it to reconnect, but i had to start ros_streamer from a completely cold state ("sweeping"/close open apps from the task switcher).

Hope that's helpful context.
