### ISSUE TITLE
Save/load 2D navigation map

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#289]
See http://wiki.ros.org/map_server

**Comment by PerrineAguiar** [comment]
@adamantivm Which repo/branch should I look to see your draft work on this?

**Comment by adamantivm** [comment]
Hi @PerrineAguiar , this is what I mentioned yesterday: https://github.com/adamantivm/tangobot/commit/acff40281f924f1202d8967b34279349928b6a95#diff-a7f851ff3694c9491c9a088fc3ff712a

It is a barely working draft, but I think it does publish the map properly.

**Comment by PerrineAguiar** [comment]
Ok, thanks!
