### ISSUE TITLE
Outdated tango_ros_node documentation

### ISSUE THREAD

**Issue by adamantivm** [Intermodalics/tango_ros#309]
The [documentation that explains how to use tango_ros_node](http://wiki.ros.org/tango_ros_streamer/tango_ros_node) from another rosjava application is grossly outdated / wrong. Some particular things to note:
 - There is no mention to the requirement to call the `/tango/connect` service in order to start publishing
 - There is no mention to the new `tango_ros_common` package, that has some required utility classes
 - There is no detail, mention or link to new utility classes and required listeners

This is making it extremely hard to be able to adopt the current published version of the tango ros streamer.

**Comment by PerrineAguiar** [comment]
Updated to doc: http://wiki.ros.org/tango_ros_streamer/tango_ros_node
