### ISSUE TITLE
ADF saving does not always get initiated after clicking on the save button

### ISSUE THREAD

**Issue by dvanthienen** [Intermodalics/tango_ros#334]
No trace on the Tango core of a saving request.

**Comment by PerrineAguiar** [comment]
After some investigation, here are some results:
* The save_map service gets called
* The Tango API `TangoService_saveAreaDescription` gets called
* After `TangoService_saveAreaDescription` get called, I can see a log message from Tango in adb logcat saying: `Stopping sensors and data processing before saving map`, but that's it, then nothing happens.
* After installing the previous version of TangoCore (Hopak), the issue does not appear anymore.
Here are the log messages I see in this case after `TangoService_saveAreaDescription` get called:
```
6-29 17:52:25.031 6034-8141/com.google.tango D/tango-hal: tango-context.cpp:Stop():356 Stop called
06-29 17:52:25.031 6034-6102/com.google.tango I/tango: tango_application.cc:1141 Stopping sensors and data processing before saving map.
06-29 17:52:25.031 6034-8141/com.google.tango D/tango-hal: tango-camera.cpp:disconnect():501 disconnect called
06-29 17:52:25.031 6034-6102/com.google.tango I/tango: tango_hal_device_wrapper.cc:187 HAL device wrapper calling stop.
```
